name: travel_tourism
description: "A new Flutter project."


publish_to: 'none' 













version: 1.0.0+1

environment:
  sdk: ^3.10.1







dependencies:
  flutter:
    sdk: flutter

  
  
  # UI & Animations
  cupertino_icons: ^1.0.8
  shimmer: ^3.0.0
  flutter_rating_bar: ^4.0.1
  intl: ^0.20.2

  # Firebase
  firebase_core: ^4.3.0
  firebase_auth: ^6.1.3
  cloud_firestore: ^6.1.1
  firebase_storage: ^13.0.5
  google_sign_in: ^6.2.1

  # Maps
  google_maps_flutter: ^2.10.0

  # State Management
  flutter_riverpod: ^2.6.1
  riverpod_annotation: ^2.6.1
  provider: ^6.1.2

  # Local Storage & Offline
  hive: ^2.2.3
  hive_flutter: ^1.1.0
  path_provider: ^2.1.3

  # Functional Programming
  freezed_annotation: ^2.4.4
  json_annotation: ^4.9.0
  http: ^1.6.0
  cached_network_image: ^3.4.1
  url_launcher: ^6.3.2
  google_fonts: ^6.3.3

dev_dependencies:
  flutter_test:
    sdk: flutter

  
  
  
  
  
  flutter_lints: ^6.0.0
  # Code Generation
  build_runner: ^2.4.13
  riverpod_generator: ^2.6.2
  freezed: ^2.5.7
  json_serializable: ^6.8.0
  flutter_launcher_icons: ^0.14.4





flutter:

  
  
  
  uses-material-design: true

  
  assets:
    - assets/images/
    - assets/Hotels/
    - assets/train/
    - assets/destinations/
    - assets/

  
  

  
  

  
  
  
  
  
  
  
  
  
  
  
  
  
  
  
  
  
  
  
